### ISSUE TITLE
Send U parameter to the tracking

### ISSUE THREAD

**Issue by jessicatsalmeida** [redpencilio/ember-plausible#29]
In our case we would need to override the `u` parameter (URL) that is sent to the `trackEvent` and `trackPageview`. For now the `u` is always the current URL, but in our case we want to redact the URL before sending it.

**Comment by Windvis** [comment]
Sorry, it seems I didn't have notifications setup for this repo, so I missed this issue. If I understand you correctly you want to pass extra options to the [`plausibleTracker.trackPageview` method](https://github.com/plausible/plausible-tracker?tab=readme-ov-file#tracking-page-views)?

It does seem that we don't accept any extra options yet: https://github.com/redpencilio/ember-plausible/blob/b3b99f2dee7b022c0bef0041896507489774f597/addon/services/plausible.js#L56-L61

This probably was an oversight in the implementation and we didn't notice because we only use the "auto page view" tracking in our apps at the moment.

I'll try to find some time to add that.

**Comment by Windvis** [comment]
Released as [v0.4.0](https://github.com/redpencilio/ember-plausible/releases/tag/v0.4.0) :+1:
